# -*- coding: utf-8 -*-
"""Notebook_Meteora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BSWzR-KB7k6G_rg0wybrlm7ZsFRy7BOO

![Alt text: Slogan da Meteora.](https://i.imgur.com/VDYh2G1.png)

# 1. Estruturando a tabela

**Meteora** é uma loja que vende roupas e acessórios de diversas marcas por todos os estados do Brasil, para entender suas bases de dados e exibir informações relevantes com o objetivo de auxiliar suas tomadas de decisão.
"""

import pandas as pd
from sqlalchemy import create_engine, inspect, text
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

"""**Sobre as tabelas**

* itens_pedidos: tabela que informa sobre o que foi vendido, vai ter informação o preço, quantidade, para onde vai ser enviado e o frete do pedido
* pedidos: vai falar sobre a venda feita, tendo informação sobre os vendedores, preço do pedido e a data da venda
* produtos: informa características dos produtos que são comercializados na loja
* vendedores: informa o nome dos vendedores.
"""

# urls com as fonte dos dados que serão utilizadas nesse novo estudo

url_itens_pedidos = 'https://github.com/alura-cursos/SQL-python-integracao/raw/main/TABELAS/itens_pedidos.csv'
url_pedidos = 'https://github.com/alura-cursos/SQL-python-integracao/raw/main/TABELAS/pedidos.csv'
url_produto = 'https://github.com/alura-cursos/SQL-python-integracao/raw/main/TABELAS/produtos.csv'
url_vendedores = 'https://github.com/alura-cursos/SQL-python-integracao/raw/main/TABELAS/vendedores.csv'

itens_pedidos = pd.read_csv(url_itens_pedidos)
pedidos = pd.read_csv(url_pedidos)
produtos = pd.read_csv(url_produto)
vendedores = pd.read_csv(url_vendedores)

"""Utilzaremos nessa estudo exploratorio o SQLite para criação dos nosso banco de dados local, assim teremos um estudo mais dinâmico e eficiente para esse caso, do que teriamos utilizando outro SGBDs."""

# criação da engine responsavel pela criação das tabelas com sqlite

engine = create_engine('sqlite:///:memory:')

pedidos.to_sql('pedidos', engine, index=False)
itens_pedidos.to_sql('itens_pedidos', engine, index=False)
produtos.to_sql('produtos', engine, index=False)
vendedores.to_sql('vendedores', engine, index=False)

# inspecionando tabelas criadas

inspector = inspect(engine)
inspector.get_table_names()

"""# 2. Primeiras consultas

Vamos entender a característica do produto que é comercializadora na Meteora, analisando a **condição** dos produtos vendidos.
"""

# definindo uma função para consulta em nosso banco de dados

def consulta(query):
  with engine.connect() as conexao:
    pesquisa = conexao.execute(text(query))
    dados = pesquisa.fetchall()
  return pd.DataFrame(dados, columns=pesquisa.keys())

# testando consulta

query = ''' SELECT CONDICAO FROM PRODUTOS '''

consulta(query)

"""Buscaremos entender como estão dispersos as condições de nossos produtos, quais são as condições existentes? E quantos produtos existem por cada condição?"""

# realizando consulta de condições

query = ''' SELECT CONDICAO, COUNT(*) AS Quantidade
FROM PRODUTOS
GROUP BY CONDICAO '''

dados_condicao = consulta(query)
dados_condicao

# criando visualização de grafico das condições dos produtos

fig = px.bar(dados_condicao, x='Condicao', y='Quantidade', color='Condicao', title='Quantidade de Produtos por Condição')
fig.update_layout(xaxis_title='', yaxis_title='')
fig.show()

"""Agora precisamos ranquear os produtos que mais foram pedidos por **quantidade** para entender a necessidade de um estoque de produtos na loja."""

# visualizando tabelas

consulta('SELECT * FROM ITENS_PEDIDOS').head(5)

consulta('SELECT * FROM PRODUTOS').head(5)

# criando query para puxar quantidade vendida por produto

query = '''SELECT ITENS_PEDIDOS.PRODUTO_ID, PRODUTOS.PRODUTO, SUM(ITENS_PEDIDOS.QUANTIDADE) AS quantidade
FROM ITENS_PEDIDOS, PRODUTOS
WHERE ITENS_PEDIDOS.PRODUTO_ID = PRODUTOS.PRODUTO_ID
GROUP BY PRODUTOS.PRODUTO
ORDER BY QUANTIDADE DESC'''

dados_quantidade = consulta(query)
dados_quantidade

# construindo grafico dos 10 produtos mais vendidos

fig = px.bar(dados_quantidade.head(10), x='quantidade', y='produto', color='produto', title='10 Produtos Mais Vendidos')
fig.update_layout(xaxis_title='Quantidade Vendida', yaxis_title='')
fig.show()

"""Continua nossa analise, veremos também quais produtos tivrem o maior volume de receita."""

# realizando query para puxarmos os dados de produtos com maiores receitas

query = ''' SELECT ITENS_PEDIDOS.PRODUTO_ID, PRODUTOS.PRODUTO, SUM(ITENS_PEDIDOS.VALOR_TOTAL) AS receita
FROM ITENS_PEDIDOS, PRODUTOS
WHERE ITENS_PEDIDOS.PRODUTO_ID = PRODUTOS.PRODUTO_ID
GROUP BY PRODUTOS.PRODUTO
ORDER BY RECEITA DESC '''

dados_receita = consulta(query)
dados_receita

# criando visualização de produtos com maiores receitas

fig = px.bar(dados_receita.head(10), x='receita', y='produto', color='produto', title='10 Produtos com Maior Receita')
fig.update_layout(xaxis_title='Receita', yaxis_title='')
fig.show()

"""Queremos agora descobrir quais foram as marcas mais pedidas em quatidade de vendas, isso pode nós ajudar a entender se temos alguma marca mais popular ou menos polular"""

# criando query para buscarmos as mais vendidas

query = ''' SELECT ITENS_PEDIDOS.PRODUTO_ID, PRODUTOS.MARCA, SUM(ITENS_PEDIDOS.QUANTIDADE) AS quantidade
FROM ITENS_PEDIDOS, PRODUTOS
WHERE ITENS_PEDIDOS.PRODUTO_ID = PRODUTOS.PRODUTO_ID
GROUP BY PRODUTOS.MARCA
ORDER BY QUANTIDADE DESC '''

dados_marca = consulta(query)
dados_marca

# criando visualização das marcas mais vendidas

fig = px.bar(dados_marca.head(5), x='marca', y='quantidade', color='marca', title='Marcas Mais Vendidas')
fig.update_layout(xaxis_title='', yaxis_title='Quantidade')
fig.show()

"""# 3. Lidando com filtro

Vamos iniciar uma análise de desempenho do **time de vendedores** da Meteora. A intenção aqui é entender como se deram as vendas dos vendedores no **ano anterior** para que possam ser aplicadas promoções e bônus salarial para a equipe no ano atual da tabela que é 2021
"""

# vamos começar verificando a tabela pedidos

consulta('SELECT * FROM PEDIDOS').head(5)

consulta('SELECT * FROM PEDIDOS').info(5)

# verificando tabela vendedores

consulta('SELECT * FROM VENDEDORES').head(5)

"""Para entender o desempenho de vendas dos vendedores no ano de 2020, é preciso trabalhar com os dados que estão presentes apenas no ano de 2020."""

# vamos filtrar apenas de 2020 com a soma das vendas dos vendedores

query = ''' SELECT PEDIDOS.VENDEDOR_ID, VENDEDORES.NOME_VENDEDOR, COUNT(PEDIDOS.TOTAL) AS quantidade_vendas
FROM PEDIDOS, VENDEDORES
WHERE strftime('%Y', PEDIDOS.DATA_COMPRA) = '2020' AND PEDIDOS.VENDEDOR_ID = VENDEDORES.VENDEDOR_ID
GROUP BY VENDEDORES.NOME_VENDEDOR
ORDER BY quantidade_vendas DESC '''

dados_vendedores = consulta(query)
dados_vendedores

# vamos agora entender quais desses vendedores teve a melhor média de vendas

query = ''' SELECT PEDIDOS.VENDEDOR_ID, VENDEDORES.NOME_VENDEDOR, AVG(PEDIDOS.TOTAL) 'media das vendas'
FROM PEDIDOS, VENDEDORES
WHERE strftime('%Y', PEDIDOS.DATA_COMPRA) = '2020' AND PEDIDOS.VENDEDOR_ID = VENDEDORES.VENDEDOR_ID
GROUP BY VENDEDORES.NOME_VENDEDOR
ORDER BY AVG(PEDIDOS.TOTAL) DESC '''

dados_vendedores = consulta(query)
dados_vendedores

"""# 4. Avançando nas relações

A Meteora agora deseja incrementar as suas vendas no **estado de São Paulo (SP)**, por acreditar ser uma região mais propícia às vendas já que tem uma boa concentração de pessoas e mercado também.

Mas será que São Paulo já não rende muitas vendas em relação a outros estados?
"""

consulta('SELECT * FROM ITENS_PEDIDOS').head(10)

# vamos puxar a quantidade de pedidos que tivemos por estado

query = '''SELECT ITENS_PEDIDOS.ESTADO, COUNT(ITENS_PEDIDOS.PEDIDO_ID) AS 'quantidade de pedidos'
FROM ITENS_PEDIDOS
GROUP BY ITENS_PEDIDOS.ESTADO
ORDER BY COUNT(ITENS_PEDIDOS.PEDIDO_ID) DESC'''

dados_estado = consulta(query)
dados_estado

"""Uma das ações que a Meteora pretende seguir para as vendas em SP é escolher dois de seus vendedores para que eles **foquem suas vendas** lá. Para essa escolha é interessante ter os profissionais que **mais tenham vendido** para as pessoas da região."""

# vamos puxar agora os vendedores com mais de pedidos no Estado SP utilizando um metodo Join

query = '''SELECT VENDEDORES.NOME_VENDEDOR, COUNT(PEDIDOS.TOTAL) AS quantidade_vendas
FROM PEDIDOS
JOIN ITENS_PEDIDOS ON ITENS_PEDIDOS.PEDIDO_ID = PEDIDOS.PEDIDO_ID
JOIN VENDEDORES ON VENDEDORES.VENDEDOR_ID = PEDIDOS.VENDEDOR_ID
WHERE ITENS_PEDIDOS.ESTADO = 'BR-SP' AND PEDIDOS.VENDEDOR_ID = VENDEDORES.VENDEDOR_ID
GROUP BY VENDEDORES.NOME_VENDEDOR
ORDER BY quantidade_vendas DESC'''

dados_vendedores = consulta(query)
dados_vendedores

"""# 5. Identificando Melhores **Resultados**

Em nosso estudo, queremos saber quais foram os produtos mais vendidos em 2019, assim teremos de como estavam nossos melhores produtos nessa epoca
"""

# vamos puxar o top 10 produtos mais vendidos de 2019

query = '''SELECT PRODUTOS.PRODUTO, COUNT(PEDIDOS.PRODUTO_ID) AS quantidade_vendida
FROM PEDIDOS
JOIN PRODUTOS ON PRODUTOS.PRODUTO_ID = PEDIDOS.PRODUTO_ID
WHERE strftime('%Y', PEDIDOS.DATA_COMPRA) = '2019' AND PEDIDOS.PRODUTO_ID = PRODUTOS.PRODUTO_ID
GROUP BY PRODUTOS.PRODUTO
ORDER BY quantidade_vendida DESC
LIMIT 10'''

dados_produtos = consulta(query)
dados_produtos

# visualização produtos mais vendidos 2019

fig = px.bar(dados_produtos, x='quantidade_vendida', y='produto', color='produto', title='Produtos Mais Vendidos em 2019')
fig.update_layout(xaxis_title='Quantidade Vendida', yaxis_title='')
fig.show()

"""Agora queremos entender como foi nossas vendas no periodo de 2020, até onde. Aonde tivemos a maior alta e a menor baixa?"""

# primeiro vamos puxar todas as vendas separadas pelos meses

query = '''SELECT strftime('%m', PEDIDOS.DATA_COMPRA) AS mes, SUM(PEDIDOS.TOTAL) AS receita
FROM PEDIDOS
WHERE strftime('%Y', PEDIDOS.DATA_COMPRA) = '2020'
GROUP BY mes
ORDER BY mes ASC'''

dados_mes = consulta(query)
dados_mes

# criando visualização dos periodo de 2020

fig = px.line(dados_mes, x='mes', y='receita', title='Vendas por Mês em 2020')
fig.update_layout(xaxis_title='Mês', yaxis_title='Receita')
fig.show()

"""# 6. Insigths para ação de Natal

A intenção da Meteora é iniciar sua ação no mês de dezembro em São Paulo, aproveitando as compras de natal para divulgar os produtos e lançar promoções para pedidos feitos nesse estado. Pensando nisso, vamos fornecer duas informações que podem contribuir na ação de dezembro.

A primeira informação é listar as marcas vendidas em São Paulo por quantidade de pedidos
"""

# vamos puxar as marcas mais vendidas no estado de São Paulo por quantidade

query = '''SELECT PRODUTOS.MARCA, COUNT(ITENS_PEDIDOS.PEDIDO_ID) AS quantidade_vendida
FROM ITENS_PEDIDOS
JOIN PRODUTOS ON PRODUTOS.PRODUTO_ID = ITENS_PEDIDOS.PRODUTO_ID
WHERE ITENS_PEDIDOS.ESTADO = 'BR-SP' AND ITENS_PEDIDOS.PRODUTO_ID = PRODUTOS.PRODUTO_ID
GROUP BY PRODUTOS.MARCA
ORDER BY quantidade_vendida DESC'''

dados_marcas = consulta(query)
dados_marcas

"""A segunda informação é publicar os produtos que são mais vendidos na época de Natal no Brasil todo."""

# puxando os produtos mais vendidos no mês de dezembro

query = '''SELECT PRODUTOS.PRODUTO, COUNT(ITENS_PEDIDOS.PEDIDO_ID) AS quantidade_vendida
FROM ITENS_PEDIDOS
JOIN PRODUTOS ON PRODUTOS.PRODUTO_ID = ITENS_PEDIDOS.PRODUTO_ID
JOIN PEDIDOS ON PEDIDOS.PEDIDO_ID = ITENS_PEDIDOS.PEDIDO_ID
WHERE strftime('%m', PEDIDOS.DATA_COMPRA) = '12'
GROUP BY PRODUTOS.PRODUTO
ORDER BY quantidade_vendida DESC'''

dados_produtos = consulta(query)
dados_produtos